/** Notice: Auto generated file, do not edit */

export const Effects: string[] = 
[
  "minecraft:absorption",
  "minecraft:bad_omen",
  "minecraft:blindness",
  "minecraft:conduit_power",
  "minecraft:darkness",
  "minecraft:fatal_poison",
  "minecraft:fire_resistance",
  "minecraft:haste",
  "minecraft:health_boost",
  "minecraft:hunger",
  "minecraft:infested",
  "minecraft:instant_damage",
  "minecraft:instant_health",
  "minecraft:invisibility",
  "minecraft:jump_boost",
  "minecraft:levitation",
  "minecraft:mining_fatigue",
  "minecraft:nausea",
  "minecraft:night_vision",
  "minecraft:oozing",
  "minecraft:poison",
  "minecraft:raid_omen",
  "minecraft:regeneration",
  "minecraft:resistance",
  "minecraft:saturation",
  "minecraft:slow_falling",
  "minecraft:slowness",
  "minecraft:speed",
  "minecraft:strength",
  "minecraft:trial_omen",
  "minecraft:village_hero",
  "minecraft:water_breathing",
  "minecraft:weakness",
  "minecraft:weaving",
  "minecraft:wind_charged",
  "minecraft:wither"
]